# Generated by Django 6.0.7 on 2026-07-27 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('auction_payment', 'Pagamento de leilão'), ('balance_recharge', 'Recarga de saldo'), ('refund', 'Estorno')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Sempre positivo — o sinal é dado pelo 'type'", max_digits=12)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(blank=True, help_text='Preenchido só em transações do tipo auction_payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='auction.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
