# Generated by Django 6.0.7 on 2026-08-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('auction_payment', 'Pagamento de leilão'), ('balance_recharge', 'Recarga de saldo'), ('refund', 'Estorno'), ('direct_purchase', 'Compra direta (mercado P2P)')], max_length=20),
        ),
    ]
