# Generated by Django 6.0.7 on 2026-07-25 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldataaccesslog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data_accesses_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personaldataaccesslog',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data_accesses_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
