# Generated by Django 6.0.7 on 2026-07-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fifa_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('formation', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('3-5-2', '3-5-2'), ('4-2-3-1', '4-2-3-1')], default='4-3-3', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('3-5-2', '3-5-2'), ('4-2-3-1', '4-2-3-1')], max_length=10)),
                ('slot_code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['formation', 'order'],
                'unique_together': {('formation', 'slot_code')},
            },
        ),
        migrations.CreateModel(
            name='TacticSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_code', models.CharField(max_length=10)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fifa_data.player')),
            ],
        ),
    ]
