# Generated by Django 6.0.7 on 2026-07-25 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tacticslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='team.team'),
        ),
        migrations.AlterUniqueTogether(
            name='tacticslot',
            unique_together={('team', 'slot_code')},
        ),
    ]
