# Generated by Django 6.0.7 on 2026-08-01 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('fifa_data', '0004_remove_player_photo_base64_player_photo'),
        ('team', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('owner', 'campaign')},
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='fifa_data.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='team.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
