# Generated by Django 6.0.7 on 2026-07-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-price', 'bid_time'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_mode', models.CharField(choices=[('player_value', 'Valor do jogador'), ('manual', 'Definido pelo admin')], default='player_value', max_length=20)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_increment', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('number_of_bids', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'aberto'), ('close', 'fechado'), ('progress', 'Em andamento'), ('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('expired', 'Expirado'), ('no_winner', 'Sem vencedor único')], default='open', max_length=10)),
                ('time_starting', models.DateTimeField()),
                ('time_ending', models.DateTimeField()),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('reopened_into', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_from', to='auction.auction')),
            ],
        ),
    ]
