# Generated by Django 6.0.7 on 2026-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('fifa_data', '0004_remove_player_photo_base64_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='player',
        ),
        migrations.AddField(
            model_name='transfer',
            name='offered_players',
            field=models.ManyToManyField(blank=True, related_name='offered_transfers', to='fifa_data.player'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='requested_players',
            field=models.ManyToManyField(blank=True, related_name='requested_transfers', to='fifa_data.player'),
        ),
    ]
