# Generated by Django 6.0.7 on 2026-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_transfer_player_transfer_offered_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='matches_per_market_cycle',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='campaign',
            name='matches_played_since_last_market',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_roster_size',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_roster_size',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='campaign',
            name='transfer_policy',
            field=models.CharField(choices=[('always_allowed', 'Sempre permitido'), ('market_window_only', 'Só durante janela de mercado')], default='market_window_only', max_length=32),
        ),
        migrations.AddField(
            model_name='marketwindow',
            name='mode',
            field=models.CharField(choices=[('auction', 'Leilão'), ('market', 'Mercado direto'), ('hybrid', 'Híbrido')], default='auction', max_length=20),
        ),
        migrations.AddField(
            model_name='marketwindow',
            name='player_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketwindow',
            name='random_selection',
            field=models.BooleanField(default=True),
        ),
    ]
