# Generated by Django 6.0.7 on 2026-08-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_created_by_marketlisting_auction'),
        ('team', '0003_team_campaign_alter_team_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayerstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='team.team'),
        ),
    ]
