# Generated by Django 6.0.7 on 2026-08-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_matches_per_market_cycle_and_more'),
        ('competitions', '0001_initial'),
        ('team', '0003_team_campaign_alter_team_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_user',
        ),
        migrations.AddField(
            model_name='competition',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='team.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='team.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='team.team'),
        ),
        migrations.RemoveField(
            model_name='competitionentry',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together={('competition', 'team')},
        ),
    ]
