# Generated by Django 6.0.7 on 2026-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competitionentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('played', 'Jogado')], default='scheduled', max_length=20),
        ),
    ]
