# Generated by Django 6.0.7 on 2026-08-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='credits_per_title',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='competition',
            name='credits_per_win',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_matches', to='competitions.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match_slot',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
