# Generated by Django 6.0.7 on 2026-07-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='version',
            new_name='best_position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='atk_work_rate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='body_type_code',
        ),
        migrations.RemoveField(
            model_name='player',
            name='buyout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='def_work_rate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='export',
        ),
        migrations.RemoveField(
            model_name='player',
            name='growth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='head_class_code',
        ),
        migrations.RemoveField(
            model_name='player',
            name='icon_trait1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='icon_trait2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='international_rep',
        ),
        migrations.RemoveField(
            model_name='player',
            name='latest_roster',
        ),
        migrations.RemoveField(
            model_name='player',
            name='play_styles',
        ),
        migrations.RemoveField(
            model_name='player',
            name='play_styles_plus',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='player',
            name='roster',
        ),
        migrations.RemoveField(
            model_name='player',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trait1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trait2',
        ),
        migrations.AddField(
            model_name='player',
            name='international_reputation',
            field=models.IntegerField(blank=True, help_text='Estrelas 1-5', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_roles',
            field=models.JSONField(blank=True, default=list, help_text='Ex: [{"role": "Wingback +", "position": "RB", "focuses": ["Balanced", "Support"]}]'),
        ),
        migrations.AddField(
            model_name='player',
            name='playstyles',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["Trivela", "Quick Step"]'),
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['RB', 'LB']"),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Não preenchido pelo scraper atual — reservado para fonte futura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='fifa_data.country'),
        ),
        migrations.AlterField(
            model_name='player',
            name='def_rating',
            field=models.IntegerField(blank=True, db_column='def_rating', help_text="Campo 'def' (renomeado para evitar conflito com keyword Python)", null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fifa_id',
            field=models.IntegerField(help_text='sofifa_id — ID do jogador no sofifa.com', unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='Não preenchido pelo scraper atual — reservado para fonte futura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='fifa_data.gender'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='marking',
            field=models.IntegerField(blank=True, help_text='Defensive awareness', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_moves',
            field=models.IntegerField(blank=True, help_text='Estrelas 1-5', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weak_foot',
            field=models.IntegerField(blank=True, help_text='Estrelas 1-5', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, help_text='kg', null=True),
        ),
    ]
