# Generated by Django 6.0.7 on 2026-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_data', '0002_rename_version_player_best_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_base64',
            field=models.TextField(blank=True, help_text="Foto do jogador já baixada e codificada como data URI base64 (ex: 'data:image/png;base64,...'). Evita depender do CDN externo do sofifa direto no <img src> do front (hotlink/CORS/expiração).", null=True),
        ),
    ]
