# Generated by Django 6.0.7 on 2026-08-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_data', '0003_player_photo_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo_base64',
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='Binário da foto baixado pelo scraper a partir de photo_url.', null=True, upload_to='player_photos/'),
        ),
    ]
